networks:
  vault-net:
    driver: bridge

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    hostname: vault.secrets
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_API_ADDR=${VAULT_API_ADDR}
      - VAULT_LOG_LEVEL=${VAULT_LOG_LEVEL}
    volumes:
      - ./config/vault/vault-config.hcl:/vault/config/vault.hcl
      - ./config/vault/vault-keys.txt:/vault/keys.txt
      - vault-data:/vault/data
      - ./config/vault/vault-entrypoint.sh:/vault-entrypoint.sh
    cap_add:
      - IPC_LOCK
    entrypoint: ["/bin/sh", "/vault-entrypoint.sh"]
    restart: unless-stopped
    networks:
      - vault-net

  nginx:
    image: nginx:latest
    container_name: nginx.secrets
    hostname: nginx.secrets
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx-config.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - vault
    restart: unless-stopped
    networks:
      - vault-net

volumes:
  vault-data:
    driver: local
    driver_opts:
      type: none
      device: ../data/vault
      o: bind
